/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "monitor_status_constants.h"

namespace infra { namespace monitor {

const monitor_statusConstants g_monitor_status_constants;

monitor_statusConstants::monitor_statusConstants() {
}

}} // namespace

