/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef monitor_entry_CONSTANTS_H
#define monitor_entry_CONSTANTS_H

#include "monitor_entry_types.h"

namespace infra { namespace monitor {

class monitor_entryConstants {
 public:
  monitor_entryConstants();

};

extern const monitor_entryConstants g_monitor_entry_constants;

}} // namespace

#endif
