/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef monitor_status_CONSTANTS_H
#define monitor_status_CONSTANTS_H

#include "monitor_status_types.h"

namespace infra { namespace monitor {

class monitor_statusConstants {
 public:
  monitor_statusConstants();

};

extern const monitor_statusConstants g_monitor_status_constants;

}} // namespace

#endif
