// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MonitorService.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::infra::monitor;

class MonitorServiceHandler : virtual public MonitorServiceIf {
 public:
  MonitorServiceHandler() {
    // Your initialization goes here
  }

  void GetServiceStatus(ServiceStatus& _return, const std::string& host_name, const std::string& service_name) {
    // Your implementation goes here
    printf("GetServiceStatus\n");
  }

  void GetServiceTypeStatus(std::vector<ServiceStatus> & _return, const std::string& service_type, const int32_t status) {
    // Your implementation goes here
    printf("GetServiceTypeStatus\n");
  }

  void SetServiceStatus(const ServiceStatus& service_status) {
    // Your implementation goes here
    printf("SetServiceStatus\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MonitorServiceHandler> handler(new MonitorServiceHandler());
  shared_ptr<TProcessor> processor(new MonitorServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

