/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "monitor_entry_constants.h"

namespace infra { namespace monitor {

const monitor_entryConstants g_monitor_entry_constants;

monitor_entryConstants::monitor_entryConstants() {
}

}} // namespace

